### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mboelen** [jacob-baines/elfparser#2]
GitHub says the project license is GPLv3, your website elfparser.com says "ELF Parser is distributed using the CC BY-NC-SA 3.0 license.". Which one is it? :)

We are reviewing your project to be listed in our [security tools](https://linuxsecurity.expert/security-tools/) section.

**Comment by jacob-baines** [comment]
Hey @mboelen, good question and sorry for the confusion. Originally, this tool was a binary only release (hence the weird CC license). After a few people asked me to release the source code, I did under GPLv3. The website has simply lagged behind the actual license.

**Comment by mboelen** [comment]
Thanks!
